SCHEDULING-1911 - Do not require JAVA_HOME to be set in scripts
jruby jar name has also been updated

Change-Id: Ia7a6d9287a7fb74a0ffa2604e86dc52893196a0b

diff --git a/bin/unix/env b/bin/unix/env
--- a/bin/unix/env
+++ b/bin/unix/env
@@ -8,16 +8,15 @@ CLASSPATH=.
 
 # ----------------------------------------------------------------------------
 
-JAVA_HOME=${JAVA_HOME-NULL};
-if [ "$JAVA_HOME" = "NULL" ]
+if [ -z "$JAVA_HOME"" ]
 then
-echo
-echo "The environment variable JAVA_HOME must be set the current jdk distribution"
-echo "installed on your computer."
-echo "Use "
-echo "    export JAVA_HOME=<the directory where is the JDK>"
-exit 127
+    JAVA=java
+else
+    JAVA=$JAVA_HOME/bin/java
 fi
+
+# Check Java available
+$JAVA -version 2> /dev/null || echo "Java could not be found in your system, configure your PATH to find java executable or define JAVA_HOME environment variable"
 
 #set Scheduler install directory env var
 
@@ -26,8 +25,8 @@ PA_SCHEDULER=$(cd $workingDir/../.././ || (echo "Broken Scheduler/Resource Manag
 print_jars() {
     # jruby.jar is put in front because jline internal package is used in the command-line interpreters
     (
-        find "$1" -name "jruby.jar"
-        find "$1" -name "*.jar" | grep -v jruby.jar
+        find "$1" -name "jruby-1.7.4.jar"
+        find "$1" -name "*.jar" | grep -v jruby-1.7.4.jar
     ) | while read jar; do
         printf "%s:" "$jar"
     done
@@ -95,7 +94,7 @@ fi
 #Enabling custom clients policy security debug (normally is enough to debug client's permissions)
 #POLICY_DEBUG="-Djava.security.debug=clients"
 
-JAVACMD=($JAVA_HOME/bin/java -Djava.security.manager -Dproactive.configuration="$PA_SCHEDULER/config/proactive/ProActiveConfiguration.xml" -Djava.security.policy="$JAVA_POLICY" $POLICY_DEBUG -Dlog4j.configuration="$LOG4J_FILE" -Dproactive.home="$PA_SCHEDULER" -Dpa.scheduler.home="$PA_SCHEDULER" -Dpa.rm.home="$PA_SCHEDULER")
+JAVACMD=($JAVA -Djava.security.manager -Dproactive.configuration="$PA_SCHEDULER/config/proactive/ProActiveConfiguration.xml" -Djava.security.policy="$JAVA_POLICY" $POLICY_DEBUG -Dlog4j.configuration="$LOG4J_FILE" -Dproactive.home="$PA_SCHEDULER" -Dpa.scheduler.home="$PA_SCHEDULER" -Dpa.rm.home="$PA_SCHEDULER")
 
 export PA_SCHEDULER
 export JAVACMD
diff --git a/bin/unix/jetty-launcher b/bin/unix/jetty-launcher
--- a/bin/unix/jetty-launcher
+++ b/bin/unix/jetty-launcher
@@ -2,6 +2,16 @@
 
 DIR=$(dirname $0)
 
+if [[ -z "$JAVA_HOME" ]]
+then
+    JAVA=java
+else
+    JAVA=$JAVA_HOME/bin/java
+fi
+
+# Check Java available
+$JAVA -version 2> /dev/null || echo "Java could not be found in your system, configure your PATH to find java executable or define JAVA_HOME environment variable"
+
 stop () {
 	echo "Error: $1";
 	echo "Use -h to print help";
@@ -35,7 +45,7 @@ mktemp_jruby() {
 	SUFFIX=".tmp"
 	export CLASSPATH=$DIR/../../dist/lib/jruby-1.7.4.jar
 	export CMD="f=Java::java.io.File.createTempFile(Java::java.lang.String.new(\"$PREFIX\"),Java::java.lang.String.new(\"$SUFFIX\"));Java::java.lang.System.out.println(f)"
-	$JAVA_HOME/bin/java -cp $CLASSPATH org.jruby.Main -e $CMD
+	$JAVA -cp $CLASSPATH org.jruby.Main -e $CMD
 }
 
 mktemp_dir_jruby() {
@@ -43,7 +53,7 @@ mktemp_dir_jruby() {
 	SUFFIX=".tmp"
 	export CLASSPATH=$DIR/../../dist/lib/jruby-1.7.4.jar
 	export CMD="f=Java::java.io.File.createTempFile(Java::java.lang.String.new(\"$PREFIX\"),Java::java.lang.String.new(\"$SUFFIX\"));f.delete();f.mkdir();Java::java.lang.System.out.println(f)"
-	$JAVA_HOME/bin/java -cp $CLASSPATH org.jruby.Main -e $CMD
+	$JAVA -cp $CLASSPATH org.jruby.Main -e $CMD
 }
 
 VERBOSE=true
@@ -180,8 +190,6 @@ if [ $SCHED ]; then
 	APPS="$APPS $SCHED_DIR"
 fi
 
-
-JAVA=$JAVA_HOME/bin/java
 
 CP=$DIR/../../dist/lib/*
 
