Added option -n to g5k_reservedNodes
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/proactive/trunk@3661 28e8926c-6b08-0410-baaa-805c5e19b8d6

diff --git a/dev/grid5000/scripts/g5k_reservedNodes b/dev/grid5000/scripts/g5k_reservedNodes
--- a/dev/grid5000/scripts/g5k_reservedNodes
+++ b/dev/grid5000/scripts/g5k_reservedNodes
@@ -3,21 +3,23 @@
 source $(dirname $0)/g5k_lib.sh
 
 function print_help {
-	echo -e "Usage: $0 [-c] [-a|-o|-c cluster] "
+	echo -e "Usage: $0 [-c] [-n num] [-a|-o|-c cluster] "
 	echo -e "Print nodes owned by a reservation\n"
 	echo -e "\t-c       , check that each node is really free (slow)"
+	echo -e "\t-n num   , print only num nodes instead of all reserved nodes"
 	modopt_print_help
 	exit 1
 }
 
-ARGS="c"
+ARGS="cn:"
 OPT_C=NO
-
+OPT_N=NO
 modopt_parse $ARGS "$@"
 while getopts "${MODOPT_OPTS}${ARGS}" Option
 do
 	case $Option in
-  c) OPT_C=YES  ;;
+	c) OPT_C=YES  ;;
+	n) OPT_N=$OPTARG ;;
 	h) print_help ;;
 	*)
 		modopt_error_handle $Option
@@ -66,23 +68,22 @@ function check_node_is_ok {
 	return 1
 } 
 
-
+OUTPUT=""
 for i in `seq 0 $((${#OPTIONS_CLUSTERS[@]}-1))` ; 
 do
 	CLUSTER=${OPTIONS_CLUSTERS[$i]}
 
-	NODES=$(cd $(dirname $0) &&	$SSH_CMD $(get_oar_hostname $CLUSTER) $PWD/g5klocal_reservedNodes)
+	NODES=$(cd $(dirname $0) && $SSH_CMD $(get_oar_hostname $CLUSTER) $PWD/g5klocal_reservedNodes)
 	if [ ! $? -eq 0 ] ;
 	then
-			echo "Cannot get reserved nodes" 1>&2
-			exit 1
+			echo $ERR_PREFIX "Cannot retrieve reserved nodes from $CLUSTER" 1>&2
+			continue
 	fi
 
 	if [ "$OPT_C" == "YES" ] ;
-  then
-		OUTPUT=""
+  	then
 		for node in $NODES ;
-    do
+    		do
 			if [ "$VERBOSE" == "Yes" ] ; then echo "Checking that $node is really free" ; fi
 			check_node_is_ok $node
 			if [ $? -eq 1 ] ;
@@ -90,9 +91,24 @@ do
 				OUTPUT="$OUTPUT $node"
 			fi
 		done
-		echo $OUTPUT
-	
 	else
-		echo $NODES
-	fi	        
+		OUTPUT="$OUTPUT $NODES"
+	fi
 done
+
+if [ "$OPT_N" = "NO" ] ;
+then
+	# Print all available nodes
+	echo $OUTPUT
+else
+	OUTPUT=$(echo $OUTPUT | cut -d" " -f 0-$OPT_N)
+	COUNT=$(echo $OUTPUT | wc -w)
+
+	echo $OUTPUT
+	if [ $COUNT -lt $OPT_N ] ; then
+		echo -e "\n"
+		echo -e "********************************************************************" 1>&2	
+		echo -e "* WARNING: You requested $OPT_N nodes but only $COUNT are available ! *" 1>&2	
+		echo -e "********************************************************************" 1>&2	
+	fi
+fi
